config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #resources :rooms
  resources :reservations
  devise_for :users
  get 'users/reservations' => 'users#reservations', as: 'reservations_user'
  #get 'reservations/show' => 'reservations#show', as: 'show_reservation'
  #post 'reservations' => 'reservations#create', as: 'create_reservation'
  root 'reservations#index'
  post 'rooms/:id/reserve' => 'rooms#reserve', as: 'reserve_room'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/navigation/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    Anything you want
  </div>
  <strong>
    Copyright © 2016
    <a href="#"> Company</a>
  </strong>
  All rights reserved.
</footer>

app/views/layouts/navigation/_header.html.erb
<header class="main-header">
  <%= link_to 'Room Reservations', root_url, class: 'logo' %>
  <nav class="navbar navbar-static-top" role="navigation">
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <% if current_user.present? %>
          <li class="dropdown user user-menu">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <img alt="User Image" class="user-image" src="http://placehold.it/160x160" />
            <span class="hidden-xs"><%= current_user.email %></span>
            </a>
            <ul class="dropdown-menu">
              <li class="user-header">
                <img class="img-circle" alt="User Image" src="http://placehold.it/160x160"> </img>
                <p>
                  <%= current_user.email %>
                  <small><%= current_user.created_at %></small>
                </p>
              </li>
              <li class="user-body">
                <div class="text-center">
                  <%= link_to 'My reservations', reservations_user_path, :class => 'navbar-link btn btn-default btn-flat' %>
                </div>
                <% if current_user.admin? %>
                  <div class="text-center">
                    <%= link_to 'Admin Panel', rails_admin_path, :class => 'navbar-link btn btn-default btn-flat' %>
                  </div>
                <% end %>
              </li>
              <li class="user-footer">
                <div class="pull-left">
                  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link btn btn-default btn-flat' %>
                </div>
                <div class="pull-right">
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link btn btn-default btn-flat'  %>
                </div>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/navigation/_layout.erb
<%= render "layouts/navigation/header" %>